// Static product data - replaces Supabase CMS

export interface Product {
  id: string;
  slug: string;
  title: string;
  description: string;
  price?: number;
  image: string;
  images: string[];
  category: string;
  subcategory: string;
  status: 'published';
  features?: string[];
  specifications?: Record<string, string>;
  seo?: { title?: string; description?: string };
}

export const products: Product[] = [
  // ───────── GARÐYRKJUBÆNDUR — Gróðurhús ─────────
  {
    id: '1',
    slug: 'grodarhus-pro-6x12',
    title: 'Gróðurhús Pro 6×12 m',
    description: 'Stöplað ál-gróðurhús hannað fyrir íslenskar aðstæður. Hentar vel fyrir fagræktendur og stór heimili.',
    price: 895000,
    image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=1200&q=80',
      'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200&q=80',
    ],
    category: 'gardyrkjubaendur',
    subcategory: 'grodur hus',
    status: 'published',
    features: ['Sterkleikuprófað fyrir 150 km/klst vind', 'Tvöföld glermengja', 'Sjálfvirkt loftræstikerfi', 'Innifalið í verði: uppsetning'],
    specifications: { 'Stærð': '6 × 12 m', 'Efni': 'Ál og herðt gler', 'Lofthæð': '3,2 m', 'Þyngd': '480 kg' },
  },
  {
    id: '2',
    slug: 'grodarhus-hobby-3x6',
    title: 'Gróðurhús Hobby 3×6 m',
    description: 'Fullkomið byrjendagróðurhús. Auðvelt í uppsetningu, hentar vel fyrir einbýlishús og sumarbústaði.',
    price: 295000,
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200&q=80',
      'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=1200&q=80',
    ],
    category: 'gardyrkjubaendur',
    subcategory: 'grodur hus',
    status: 'published',
    features: ['Pólýkarbonat veggir', 'Einföld hurð', 'Þakgluggi til loftræstingar'],
    specifications: { 'Stærð': '3 × 6 m', 'Efni': 'Ál og pólýkarbonat', 'Lofthæð': '2,5 m' },
  },
  {
    id: '3',
    slug: 'grodarhus-commercial-10x20',
    title: 'Atvinnugróðurhús 10×20 m',
    description: 'Stór atvinnuhúsnæði með fullu loftræstikerfi, hitun og LED lýsingu. Hannað fyrir stóra framleiðendur.',
    price: 4200000,
    image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=1200&q=80',
      'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=1200&q=80',
    ],
    category: 'gardyrkjubaendur',
    subcategory: 'grodur hus',
    status: 'published',
    features: ['Sjálfvirkt hitastýringarkerfi', 'Innbyggð skuggahjúpur', 'Rafrænir gluggar', 'Substrát-ræktunarbekkir'],
    specifications: { 'Stærð': '10 × 20 m', 'Hlutfall gler': '90%', 'Hitun': 'Vatnshiti' },
  },

  // ───────── GARÐYRKJUBÆNDUR — Varmastýring ─────────
  {
    id: '10',
    slug: 'hitastyringarkerfi-argus',
    title: 'Hitastýringarkerfi Argus',
    description: 'Sjálfvirkt hitastýringarkerfi fyrir gróðurhús. Stýrir hita, raka og CO₂ – fjarstýrt í gegnum app.',
    price: 350000,
    image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=1200&q=80'],
    category: 'gardyrkjubaendur',
    subcategory: 'varmast yring',
    status: 'published',
    features: ['App-stýring (iOS/Android)', 'Sjálfvirkur viðvörunarmaður', 'Tengist Wifi'],
    specifications: { 'Hitasvigrúm': '-20°C til 50°C', 'Rakaþröskuldar': '0–100% RH', 'Tengingar': '8 x rásir' },
  },
  {
    id: '11',
    slug: 'rafmagnsofn-grodarhus-2kw',
    title: 'Rafmagnsofn fyrir Gróðurhús 2 kW',
    description: 'Þéttlægur hitaofn sem hentar vel fyrir lítil til meðalstór gróðurhús. Með hitastjóra.',
    price: 45000,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80'],
    category: 'gardyrkjubaendur',
    subcategory: 'varmast yring',
    status: 'published',
    features: ['Innbyggður hitastjóri', 'IP44 vatnslokun', 'Stilling 0–50°C'],
    specifications: { 'Afl': '2000 W', 'Spenna': '230 V', 'Þyngd': '3 kg' },
  },

  // ───────── GARÐYRKJUBÆNDUR — Ræktunarkassar ─────────
  {
    id: '20',
    slug: 'raektunarkassar-nft-6rasa',
    title: 'NFT Ræktunarkassar – 6 rásir',
    description: 'NFT-kerfi (Nutrient Film Technique) fyrir vatnslósa ræktun. Tilvalið fyrir salat, jurtir og grænmeti.',
    price: 185000,
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200&q=80'],
    category: 'gardyrkjubaendur',
    subcategory: 'raektunarkassar',
    status: 'published',
    features: ['6 rásir × 2 m', 'Innbyggð næringardæla', 'Þéttnisforrit fylgir'],
    specifications: { 'Heildarrými': '36 plöntur', 'Vatnsnotkun': '-70% vs jarðrækt', 'Efni': 'Matvælaþolið PVC' },
  },
  {
    id: '21',
    slug: 'deep-water-culture-tank-100l',
    title: 'DWC Ræktunartankur 100 L',
    description: 'Deep Water Culture kerfi fyrir stórar plöntur eins og tómatar, paprikur og gúrkur.',
    price: 89000,
    image: 'https://images.unsplash.com/photo-1592419044706-39796d40f98c?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1592419044706-39796d40f98c?w=1200&q=80'],
    category: 'gardyrkjubaendur',
    subcategory: 'raektunarkassar',
    status: 'published',
    features: ['100 L tankur', 'Loftdæla og loftsteinar', 'Svifande ræktunarpallur'],
    specifications: { 'Rúmmál': '100 L', 'Plöntur': 'Allt að 12', 'Efni': 'HDPE matvælaþolið' },
  },

  // ───────── GARÐYRKJUBÆNDUR — Vökvunarkerfi ─────────
  {
    id: '30',
    slug: 'dropvokvunarkerfi-50-plontur',
    title: 'Droppvökvunarkerfi – 50 plöntur',
    description: 'Sjálfvirkt droppvökvunarkerfi sem hentar vel fyrir gróðurhús og útiræktun. Easy-set tímasetjari.',
    price: 38500,
    image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=1200&q=80'],
    category: 'gardyrkjubaendur',
    subcategory: 'vokvunarkerfi',
    status: 'published',
    features: ['Tímasetjari 16 forrit', 'Dreifikæla og slöngur meðfylgja', 'Stendur undir 3 bar þrýstingi'],
    specifications: { 'Fjöldi dropa': '50', 'Slöngu-lengd': '15 m', 'Þrýstingur': '1–3 bar' },
  },
  {
    id: '31',
    slug: 'vokvunardaela-grundfos-cm',
    title: 'Vökvunardæla Grundfos CM',
    description: 'Áreiðanleg Grundfos dæla fyrir vökvunarkerfi. Þolir langan þvermál og háþrýsting.',
    price: 125000,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80'],
    category: 'gardyrkjubaendur',
    subcategory: 'vokvunarkerfi',
    status: 'published',
    features: ['Ryðfrítt stál', 'Sjálfvirk þrýstingsstýring', 'IE3 hreyfilstuðull'],
    specifications: { 'Flæðimagn': 'Allt að 3,6 m³/klst', 'Hæð': 'Allt að 62 m', 'Afl': '0,37 kW' },
  },

  // ───────── GARÐYRKJUBÆNDUR — LED ljósabúnaður ─────────
  {
    id: '40',
    slug: 'led-vaxtarljus-630w-samsung',
    title: 'LED Vaxtarljós 630W Samsung',
    description: 'Fullspektrum LED vaxtarljós með Samsung dioda. Lægri hitamyndun og minni rafmagnsnotkun en HPS.',
    price: 195000,
    image: 'https://images.unsplash.com/photo-1558904541-efa843a96f01?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1558904541-efa843a96f01?w=1200&q=80'],
    category: 'gardyrkjubaendur',
    subcategory: 'led-ljosabunadur',
    status: 'published',
    features: ['Samsung LM301H dioda', 'PPF: 1700 µmol/s', 'Lífslíkur: 50.000 klst', 'Lágt hitastig'],
    specifications: { 'Afl': '630 W', 'Ljóssvigrúm': '390–780 nm', 'Hiti': '<35°C', 'Mál (L×W)': '120 × 60 cm' },
  },
  {
    id: '41',
    slug: 'led-vaxtarljus-120w-hobby',
    title: 'LED Vaxtarljós 120W Hobby',
    description: 'Sérhannað LED ljós fyrir smáa gróðurhúsa og innræktun. Kemur með hengingartaumum.',
    price: 39000,
    image: 'https://images.unsplash.com/photo-1558904541-efa843a96f01?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1558904541-efa843a96f01?w=1200&q=80'],
    category: 'gardyrkjubaendur',
    subcategory: 'led-ljosabunadur',
    status: 'published',
    features: ['Fullspektrum 3000K + 6500K', 'Ljósstyrkjastillir', 'Meðfylgja hengingartaumar'],
    specifications: { 'Afl': '120 W', 'Þekjusvæði': '60 × 60 cm', 'Lífslíkur': '30.000 klst' },
  },

  // ───────── GARÐYRKJUBÆNDUR — Hitastigar og mælar ─────────
  {
    id: '50',
    slug: 'wifi-umhverfismaelir-aranet4',
    title: 'Umhverfismælir Aranet4',
    description: 'Þráðlaust CO₂-, hita- og rakamælitæki með e-ink skjá. Sýnir gögn í rauntíma í app.',
    price: 49000,
    image: 'https://images.unsplash.com/photo-1617576683096-00fc8eecb3af?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1617576683096-00fc8eecb3af?w=1200&q=80'],
    category: 'gardyrkjubaendur',
    subcategory: 'hitastigar-og-maelar',
    status: 'published',
    features: ['CO₂, hiti, raki og loftþrýstingur', 'Bluetooth + app', 'Rafhlöðuendingur 2 ár'],
    specifications: { 'CO₂-svigrúm': '0–9999 ppm', 'Nákvæmni': '±50 ppm', 'Endingartími': '2 ár' },
  },
  {
    id: '51',
    slug: 'jardhitamaelir-tensiometer',
    title: 'Jarðhitamælir – Tensiometer',
    description: 'Gefur nákvæmt yfirlit yfir jarðvegsraka og hjálpar til við að skipuleggja vökvun rétt.',
    price: 18500,
    image: 'https://images.unsplash.com/photo-1617576683096-00fc8eecb3af?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1617576683096-00fc8eecb3af?w=1200&q=80'],
    category: 'gardyrkjubaendur',
    subcategory: 'hitastigar-og-maelar',
    status: 'published',
    features: ['Rafhlauðulaus notun', 'Djúpur 30 cm skynjar', 'Auðlesanlegur barometer'],
    specifications: { 'Dýpt': '30 cm', 'Svigrúm': '0–100 cb', 'Efni': 'Ryðfrítt stál' },
  },

  // ─────────────── LANDBÚNAÐUR — Garðyrkjuvélar ───────────────
  {
    id: '100',
    slug: 'dreifaravagn-pro-500l',
    title: 'Dreifavagn Pro 500 L',
    description: 'Stór dreifavagn fyrir áburð og jarðveg, hentar vel fyrir stærri lóðir og bújörður.',
    price: 650000,
    image: 'https://images.unsplash.com/photo-1625246286509-bc46934c3a9f?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1625246286509-bc46934c3a9f?w=1200&q=80'],
    category: 'landbunadur',
    subcategory: 'gardyrkjuvelar',
    status: 'published',
    features: ['500 L rúmmál', 'Stálbygging', 'Hentar fyrir traktor'],
    specifications: { 'Rúmmál': '500 L', 'Þyngd': '350 kg', 'Breidd': '1,8 m' },
  },
  {
    id: '101',
    slug: 'minigravari-kubota-u10',
    title: 'Minigravar Kubota U10',
    description: 'Lítill og kraftmikill minigravar. Fullkominn fyrir lítil garðverkefni og jarðfræðiskoðun.',
    price: 3800000,
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&q=80'],
    category: 'landbunadur',
    subcategory: 'gardyrkjuvelar',
    status: 'published',
    features: ['Kubota 10 hestöfl', 'Snúningshringur 360°', 'Hraðar tengingar á skurðar'],
    specifications: { 'Hestöfl': '10 HP', 'Þyngd': '1050 kg', 'Skurðardýpt': '1,88 m' },
  },

  // ─────────────── LANDBÚNAÐUR — Slátturvélar ───────────────
  {
    id: '110',
    slug: 'husqvarna-lc247s-slattuvél',
    title: 'Husqvarna LC247S Slátturvél',
    description: 'Áreiðanleg bensínknúin slátturvél með hreyfidrif. Hentar vel fyrir meðalstórar lóðir.',
    price: 135000,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80'],
    category: 'landbunadur',
    subcategory: 'slatturvelar',
    status: 'published',
    features: ['Honda GCV 140 hreyfill', 'Hreyfidrif', 'Geymsluþjöppun', 'Breidd: 47 cm'],
    specifications: { 'Hreyfill': 'Honda GCV140', 'Breidd': '47 cm', 'Þyngd': '32 kg' },
  },
  {
    id: '111',
    slug: 'robotslatturvél-gardena-sileno',
    title: 'Robotslátturvél Gardena Sileno',
    description: 'Sjálfvirk robotslátturvél með GPS-kortlagningu. Sláttar eingöngu þegar þarf og skilar þurrkuðum grasbreiðum.',
    price: 380000,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80'],
    category: 'landbunadur',
    subcategory: 'slatturvelar',
    status: 'published',
    features: ['GPS kortlagning', 'Regn- og þefskynjarar', 'App-stýring', 'Rafhlöðu: 5 klst'],
    specifications: { 'Lóðarflötur': 'Allt að 1250 m²', 'Hlutfall': '35°', 'Þyngd': '8,4 kg' },
  },

  // ─────────────── LANDBÚNAÐUR — Sáningabúnaður ───────────────
  {
    id: '120',
    slug: 'hondahefill-fx21-saningavél',
    title: 'Sáningavél Honda FX21',
    description: 'Kraftmikil sáningavél sem dreifir fræi jafnt. Hentar vel fyrir stórar lóðir og slóttir.',
    price: 220000,
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=1200&q=80'],
    category: 'landbunadur',
    subcategory: 'saningabunadur',
    status: 'published',
    features: ['Honda GX160 hreyfill', 'Dreifist á 1,2 m breidd', '25 L frægeymslufat'],
    specifications: { 'Dreifbreidd': '1,2 m', 'Geymslufat': '25 L', 'Breidd': '68 cm' },
  },

  // ─────────────── LANDBÚNAÐUR — Heyvinnsla ───────────────
  {
    id: '130',
    slug: 'heysturar-kuhn-ga4531',
    title: 'Heysturar Kuhn GA 4531',
    description: 'Gæðatæki fyrir heysturun á bújörðum. Þolir þungt álag og stendur undir langtímanotkunar.',
    price: 1200000,
    image: 'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?w=1200&q=80'],
    category: 'landbunadur',
    subcategory: 'heyvinnsla',
    status: 'published',
    features: ['Vinnubreidd: 4,5 m', 'Tvíhverfar armar', 'Hentar til traktor PTO'],
    specifications: { 'Vinnubreidd': '4,5 m', 'Þyngd': '560 kg', 'PTO': '540 snúningar' },
  },

  // ─────────────── LANDBÚNAÐUR — Girðingaefni ───────────────
  {
    id: '140',
    slug: 'rafmagnsgirdingarvél-litzener',
    title: 'Rafmagnsgirðingarvél Litzener',
    description: 'Kraftmikil og áreiðanleg rafmagnsgirðingarvél. Hentar vel fyrir búfé og varnargarða.',
    price: 75000,
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1560250097-0b93528c311a?w=1200&q=80'],
    category: 'landbunadur',
    subcategory: 'girdingaefni',
    status: 'published',
    features: ['10 J úttaksspenning', 'Stendur undir öllum veðri', 'Innbyggður LED-vísi'],
    specifications: { 'Úttaksspenning': '10 J', 'Spenna': '9 000 V', 'Batteries': '9 V eða rafmagn' },
  },
  {
    id: '141',
    slug: 'girdingarstaurar-galvaneradir-2m',
    title: 'Girðingarstaurar galvaniseraðir 2 m (20 stk)',
    description: 'Galvaniseraðir staurar sem endast í íslenskum jarðvegi og veðri. Sekkjapakki með 20 stk.',
    price: 22000,
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1560250097-0b93528c311a?w=1200&q=80'],
    category: 'landbunadur',
    subcategory: 'girdingaefni',
    status: 'published',
    features: ['Galvaneraðir í 80 µm', 'Hvassur endir', 'Þykkt: 4 mm'],
    specifications: { 'Hæð': '200 cm', 'Þykkt': '4 mm', 'Pakki': '20 stk' },
  },

  // ─────────────── LANDBÚNAÐUR — Hlaðabúnaður ───────────────
  {
    id: '150',
    slug: 'hladabjorn-flaeksibill-800kg',
    title: 'Hlaðabjörn Flaeksbill 800 kg',
    description: 'Gafflabjörn sem hentar við söfnun heys og annars byrðar. 800 kg burðarþol.',
    price: 185000,
    image: 'https://images.unsplash.com/photo-1560869713-7d0a29430803?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1560869713-7d0a29430803?w=1200&q=80'],
    category: 'landbunadur',
    subcategory: 'hladabunadur',
    status: 'published',
    features: ['800 kg burðarþol', 'Galvaniserat stál', 'Hentar bæði inni og úti'],
    specifications: { 'Burðarþol': '800 kg', 'Breidd': '1,2 m', 'Þyngd': '65 kg' },
  },

  // ─────── ALMENNAR GARÐVÖRUR — Garðverkfæri ───────
  {
    id: '200',
    slug: 'fiskars-vinnulandaset-5-hlutir',
    title: 'Fiskars Vinnulandasett – 5 hlutir',
    description: 'Vandað Fiskars garðverkfærasett með spöðu, gröf, hörfu og fleira. Ergonómisar handföng.',
    price: 39000,
    image: 'https://images.unsplash.com/photo-1617576683096-00fc8eecb3af?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1617576683096-00fc8eecb3af?w=1200&q=80'],
    category: 'almennar-gardyrkjuvorur',
    subcategory: 'gardverkfaeri',
    status: 'published',
    features: ['Ergonómisar handföng', 'Ryðfrítt stál', '5 ára ábyrgð'],
    specifications: { 'Efni': 'Ryðfrítt stál + plasthandföng', 'Pakki': '5 hlutir', 'Þyngd': '3,5 kg' },
  },
  {
    id: '201',
    slug: 'hakkt-handklippar-bypass-felco-2',
    title: 'Handklippar Felco 2 Bypass',
    description: 'Íslenski faggarðyrkjumaðurinn notar Felco. Þessar klippugar standast áratugi.',
    price: 14500,
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200&q=80'],
    category: 'almennar-gardyrkjuvorur',
    subcategory: 'gardverkfaeri',
    status: 'published',
    features: ['Bypassblað úr hertu stáli', 'Stálhandföng', 'Viðskiptanlegar hlutir', 'Lífstímaábyrgð'],
    specifications: { 'Bol': 'Ál', 'Blað': 'Hert stál', 'Þyngd': '235 g' },
  },
  {
    id: '202',
    slug: 'stikaraspade-bully-forged',
    title: 'Stíkuraspaði Bully Forged',
    description: 'Járnsmíðaður spade sem þolir þungt grjót og rótarverkefni. "The Tools Professionals Choose."',
    price: 18000,
    image: 'https://images.unsplash.com/photo-1617576683096-00fc8eecb3af?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1617576683096-00fc8eecb3af?w=1200&q=80'],
    category: 'almennar-gardyrkjuvorur',
    subcategory: 'gardverkfaeri',
    status: 'published',
    features: ['Järnsmíðaður bladsskaftur', 'Hickory tréhandföng', 'Staðlaðar mál'],
    specifications: { 'Lengd': '115 cm', 'Blað': 'Forged stál', 'Þyngd': '1,8 kg' },
  },

  // ─────── ALMENNAR GARÐVÖRUR — Garðhúsgögn ───────
  {
    id: '210',
    slug: 'timburbordsett-teak-6-mann',
    title: 'Timburborsett Teak – 6 manna',
    description: 'Vandað teakviðar borðsett sem þolir íslenskt veður. Kemur sett saman og tilbúið til notkunar.',
    price: 245000,
    image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80'],
    category: 'almennar-gardyrkjuvorur',
    subcategory: 'gardhusgo gn',
    status: 'published',
    features: ['FSC-vottað teak', 'Þolir regn og snjó', 'Kemmur saman sett'],
    specifications: { 'Borðstærð': '200 × 100 cm', 'Þyngd': '68 kg', 'Borðstólar': '6 + 1 borð' },
  },
  {
    id: '211',
    slug: 'aluminium-adstolusetrid-lifi',
    title: 'Ál adstólasett Lifi – 4 einingar',
    description: '4 stykja ál-adstólasett með háþrýstiþvegnum kuðungar. Létt og þolið.',
    price: 145000,
    image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80'],
    category: 'almennar-gardyrkjuvorur',
    subcategory: 'gardhusgo gn',
    status: 'published',
    features: ['Ál-rammi', 'Vatnsþolnar kuðungar', 'Einfaldar samsetningar'],
    specifications: { 'Efni': 'Ál + polyester', 'Þyngd': '28 kg', 'Pakki': '4 stólar + borð' },
  },

  // ─────── ALMENNAR GARÐVÖRUR — Pottaplöntur ───────
  {
    id: '220',
    slug: 'monstera-deliciosa-4-liter',
    title: 'Monstera Deliciosa – 4L pottur',
    description: 'Vinsæl inniplanta sem gefur fallegt útlit með stórum slísuplöntuleggjum.',
    price: 6900,
    image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=1200&q=80'],
    category: 'almennar-gardyrkjuvorur',
    subcategory: 'pottaplantur',
    status: 'published',
    features: ['Auðveld í umönnun', 'Hreinsar loft', 'Hentar vel á innri stöðum'],
    specifications: { 'Pottastærð': '4 L', 'Hæð': '40–60 cm', 'Ljós': 'Hlutskuggi' },
  },
  {
    id: '221',
    slug: 'ficuspalmur-robusta-14l',
    title: 'Ficus Robusta – 14L pottur',
    description: 'Stór og glæsileg inniplanta. Þolir þurrkur og hentar vel í stórum rýmum.',
    price: 18500,
    image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=1200&q=80'],
    category: 'almennar-gardyrkjuvorur',
    subcategory: 'pottaplantur',
    status: 'published',
    features: ['Mjög bíðin við þurrkur', 'Hreinsar loft', 'Hægt að þjálfa í trjáform'],
    specifications: { 'Pottastærð': '14 L', 'Hæð': '80–120 cm', 'Ljós': 'Beint eða óbeint' },
  },

  // ─────── ALMENNAR GARÐVÖRUR — Jarðvegur og áburður ───────
  {
    id: '230',
    slug: 'groemold-universal-70l',
    title: 'Grœmold Universal Jarðvegur 70 L',
    description: 'Íslenskt jarðvegsblöndur sérsniðin að íslenskum ræktunarskilyrðum. Auðgar jarðveg og eykur gróðursett.',
    price: 4990,
    image: 'https://images.unsplash.com/photo-1625246286509-bc46934c3a9f?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1625246286509-bc46934c3a9f?w=1200&q=80'],
    category: 'almennar-gardyrkjuvorur',
    subcategory: 'jardvegur-aburur',
    status: 'published',
    features: ['pH 5,5–6,5', 'Inniheldur perlit og mó', 'Peat-free valkostur fáanlegur'],
    specifications: { 'Rúmmál': '70 L', 'pH': '5,5–6,5', 'EC': '1,5 mS/cm' },
  },
  {
    id: '231',
    slug: 'yaramiila-pk-aburur-25kg',
    title: 'Yara Mila PKS Áburður 25 kg',
    description: 'Granúleraður PKS-áburður frá Yara. Eykur rótarþróun og blómsetningu á grænmeti og blóm.',
    price: 7500,
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200&q=80'],
    category: 'almennar-gardyrkjuvorur',
    subcategory: 'jardvegur-aburur',
    status: 'published',
    features: ['Granúlerað – auðvelt að dreifa', 'PKS 4-20-20', 'Hraðverkandi'],
    specifications: { 'Þyngd': '25 kg', 'NPK-hlutfall': '4-20-20', 'Nota': '30–50 g/m²' },
  },

  // ─────── ALMENNAR GARÐVÖRUR — Girðingar og skreyting ───────
  {
    id: '240',
    slug: 'bambusgirdingar-tall-1m-2m-10pk',
    title: 'Bambusgirðing 1×2 m – 10 stk pakki',
    description: 'Náttúruteg bambusgirðing til skreytingar og friðhelgisgæslu. Auðveld uppsetning.',
    price: 15900,
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1560250097-0b93528c311a?w=1200&q=80'],
    category: 'almennar-gardyrkjuvorur',
    subcategory: 'girdingar-skreyting',
    status: 'published',
    features: ['Náttúrulegar bambusrör', 'Þolir rigninguna', 'Auðveld uppsetning'],
    specifications: { 'Hæð': '1 m', 'Breidd': '2 m', 'Pakki': '10 stk' },
  },
  {
    id: '241',
    slug: 'led-gardskreyting-solar-20m',
    title: 'LED Garðskreytingarljós Sólarknúin 20 m',
    description: 'Sólarknúin LED ljósakeðja fyrir garðinn. Kveikist sjálfvirkt við myrkur. 200 LED-perur.',
    price: 8900,
    image: 'https://images.unsplash.com/photo-1558904541-efa843a96f01?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1558904541-efa843a96f01?w=1200&q=80'],
    category: 'almennar-gardyrkjuvorur',
    subcategory: 'girdingar-skreyting',
    status: 'published',
    features: ['200 LED-perur', 'Sólarknúin – enginn rafmagnskostur', 'IP65 vatnþéttleiki', 'Sjálfvirkt ljóskynjari'],
    specifications: { 'Lengd': '20 m', 'Perur': '200 × LED', 'Hlöðun': 'Sólarrafhlöður' },
  },

  // ─────── ALMENNAR GARÐVÖRUR — Vatnsslöngur ───────
  {
    id: '250',
    slug: 'gardena-comfort-slong-25m',
    title: 'Gardena Comfort Slanga 25 m',
    description: 'Þrýstisþolin garðaslanga frá Gardena. Verdur ekki slétt og þolir frostinn vel.',
    price: 16900,
    image: 'https://images.unsplash.com/photo-1558904541-efa843a96f01?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1558904541-efa843a96f01?w=1200&q=80'],
    category: 'almennar-gardyrkjuvorur',
    subcategory: 'vatnsslongur',
    status: 'published',
    features: ['25 m', '5-laga bygging', 'Þolir 25 bar', 'Gardena tenging'],
    specifications: { 'Lengd': '25 m', 'Þvermál': '13 mm (1/2\")', 'Þrýstimit': '25 bar' },
  },
  {
    id: '251',
    slug: 'plasson-droppslonga-50m-samansett',
    title: 'Droppslanga Plasson 50 m – Samsett',
    description: 'Tilbúið droppvökvunarkerfi fyrir blómabeð og grænmetisgarð. 50 m slanga með 100 dropa.',
    price: 24500,
    image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=1200&q=80'],
    category: 'almennar-gardyrkjuvorur',
    subcategory: 'vatnsslongur',
    status: 'published',
    features: ['50 m slanga', '100 dropa á 50 cm bili', 'Kemur sett saman', 'Matvælaþolið efni'],
    specifications: { 'Lengd': '50 m', 'Dropa': '100 stk', 'Flæðimagn': '2 L/klst per dropa' },
  },
];

// Helper to get products by category and subcategory
export function getProductsBySubcategory(category: string, subcategory: string): Product[] {
  return products.filter(
    (p) => p.category === category && p.subcategory === subcategory
  );
}

// Helper to get a product by slug
export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

// Helper to get featured products (first 6 published)
export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.status === 'published').slice(0, 6);
}
